; PlatformIO Project Configuration File for AQUAPULSE Firmware
[platformio]
default_envs = esp32s3_node

[env:esp32s3_node]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags = 
    -I include
    -I src
    -O3

[env:stm32h7_node]
platform = ststm32
board = nucleo_h743zi
framework = stm32cube
monitor_speed = 115200
build_flags = 
    -I include
    -I src
    -O3
